#!/usr/bin/env bash
set -Eeuxo pipefail

setup_dist_bins() {
  mkdir -p dist/bin
  # Copy over each binary (built with --release) listed in Cargo.toml.
  for bin in $(cargo read-manifest | jq -r '.targets[] | select([ .kind[] | contains("bin") ] | any) | .name'); do
    cp "target/release/$bin" "dist/bin/$bin";
  done
}

zip_dist() {
  name="$1"
  cp -Lr rlibs dist/rlibs
  cp -r dist "$name"
  tar -czf "$name".tar.gz "$name"
}

# Download `simple-json-schema` and run it on mir-json files generated by 
# the tests.   As a result, this should be run *after*
# running the tests, so that the tests generate some `*.linked-mir.json` files
# to validate here.
validate_json_schema() {
  URL=https://github.com/GaloisInc/simple-json-schema/releases/download/$VER/simple-json-schema-$VER-$OS_TAG-$ARCH_TAG
  curl -L "$URL" -o simple-json-schema
  chmod +x simple-json-schema
  for i in $(find . -name '*.linked-mir.json'); do
    ./simple-json-schema doc/mir-json-schema.ts --validate=$i
  done
}

COMMAND="$1"
shift

"$COMMAND" "$@"
