version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Only propose minor or patch updates to cargo dependencies, as these are
      # much more likely to be backwards-compatible than major updates.
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
