#!/usr/bin/env bash

set -e

require_tool() {
    local TOOL_EXEC="$1"
    local TOOL_NAME="$2"
    set +e
    TOOL_PATH=$(which "${TOOL_EXEC}")
    if [[ "$?" != 0 ]]; then
        echo "This script requires ${TOOL_NAME}"
        exit 1
    fi
    set -e
}

require_rust_component() {
    local COMPONENT_NAME="$1"
    if [[ $(rustup component list --toolchain "${MIR_JSON_RUST_TOOLCHAIN}" --installed | grep -c "^${COMPONENT_NAME}") == 0 ]]; then
        echo "Building mir-json requires the Rust component ${COMPONENT_NAME}; install it with"
        echo "  rustup component add --toolchain \"${MIR_JSON_RUST_TOOLCHAIN}\" ${COMPONENT_NAME}"
        exit 1
    fi
}

# Need 'git' to download 'mir-json', 'cc' to run the compiler,
# and 'rustup' to handle Rust dependencies.
check_tools() {
    require_tool cc "a C compiler"
    require_tool git "Git"
    require_tool rustup "Rustup"
}

check_rust_toolchain() {
    if [[ $(rustup toolchain list | grep "${MIR_JSON_RUST_TOOLCHAIN}") == "" ]]; then
        echo "Building mir-json requires the Rust toolchain ${MIR_JSON_RUST_TOOLCHAIN}; install it with"
        echo "  rustup toolchain install ${MIR_JSON_RUST_TOOLCHAIN}"
        exit 1
    fi
    if [[ $(rustup target list --installed | grep "${TARGET_TRIPLET}") == "" ]]; then
        echo "Target ${TARGET_TRIPLET} not installed; install with"
        echo "  rustup target add ${TARGET_TRIPLET}"
        exit 1
    fi
}

get_toolchain_dir() {
    local VERSION="${1:-${MIR_JSON_VERSION}}" 
    local TOOLCHAIN="${2:-${MIR_JSON_RUST_TOOLCHAIN}}"
    local TARGET="${3:-${TARGET_TRIPLET}}"
    echo "${MIR_JSON_INSTALL_DIR}/toolchains/${VERSION}/${TOOLCHAIN}/${TARGET}"
}

get_mir_json_src() {
    local MIR_JSON_SRC_DIR="$(get_toolchain_dir)/src"
    mkdir -p "${MIR_JSON_SRC_DIR}"
    cd "${MIR_JSON_SRC_DIR}"
    if ! [[ -d mir-json ]]; then
        git clone https://github.com/GaloisInc/mir-json.git
    fi
    cd mir-json
    set +e
    if [[ $(git show-ref refs/tags/"${MIR_JSON_VERSION}") == "" ]]; then
        git pull
    fi
    set -e
    git checkout "${MIR_JSON_VERSION}"
}

create_installation_dir() {
    if [[ -d "${MIR_JSON_INSTALL_DIR}/default/bin" ]]; then
          rm -rf "${MIR_JSON_INSTALL_DIR}/default/bin"
    fi
    mkdir -p "${MIR_JSON_INSTALL_DIR}/default/bin"
    cd "${MIR_JSON_INSTALL_DIR}/default/bin"
    ln -s ../../mir-json-up
    if [[ ! -e "${MIR_JSON_INSTALL_DIR}/mir-json-up" ]]; then
         cp "${SCRIPT_FILE}" "${MIR_JSON_INSTALL_DIR}/mir-json-up"
    fi
}

create_default_symlinks() {
    local TOOLCHAIN_DIR="$1"
    local MIR_JSON_SRC_DIR="${TOOLCHAIN_DIR}/src"
    local MIR_JSON_BIN_DIR="${TOOLCHAIN_DIR}/bin/${TARGET_TRIPLET}/release"
    local MIR_JSON_RLIBS_DIR="${TOOLCHAIN_DIR}/rlibs"

    if [[ -d "${MIR_JSON_INSTALL_DIR}/default" ]]; then
        rm -rf "${MIR_JSON_INSTALL_DIR}/default"
    fi
    create_installation_dir
    for execFile in $(find "${MIR_JSON_BIN_DIR}" -maxdepth 1 -type f); do
        if [[ -x "${execFile}" ]]; then
            ln -s "${execFile}"
        fi
    done
    cd ..
    ln -s "${MIR_JSON_RLIBS_DIR}" rlibs
}

build_mir_json() {
    local MIR_JSON_SRC_DIR="$(get_toolchain_dir)/src"
    local MIR_JSON_BIN_DIR="$(get_toolchain_dir)/bin"
    local MIR_JSON_RLIBS_DIR="$(get_toolchain_dir)/rlibs"
    mkdir -p "${MIR_JSON_BIN_DIR}"
    cd "${MIR_JSON_SRC_DIR}/mir-json"
    cargo +"${MIR_JSON_RUST_TOOLCHAIN}" build -r --target "${TARGET_TRIPLET}" --target-dir "${MIR_JSON_BIN_DIR}" --locked
    PATH="${MIR_JSON_BIN_DIR}/${TARGET_TRIPLET}/release:$PATH"
    echo $PATH
    mir-json-translate-libs --target "${TARGET_TRIPLET}"
    if [[ $? == 0 ]]; then
        if [[ -e "${MIR_JSON_RLIBS_DIR}" ]]; then
            rm -rfv "${MIR_JSON_RLIBS_DIR}"
        fi
        cp -RL rlibs "${MIR_JSON_RLIBS_DIR}"
    fi
    if [[ ! -d "${MIR_JSON_INSTALL_DIR}/default/bin/mir-json" ]]; then
        create_default_symlinks "$(get_toolchain_dir)"
    fi
}

get_toolchain_from_version() {
    local VERSION="${1:-${MIR_JSON_VERSION}}"
    case "$VERSION" in
       *)
           echo "nightly-2025-09-14"
           ;;
    esac
}

target_triplet_from_cc() {
    local TRIPLET=$(cc -dumpmachine)
    case "$TRIPLET" in
        x86_64-linux-gnu)
           echo "x86_64-unknown-linux-gnu"
           ;;
        arm64-apple-darwin*)
           echo "aarch64-apple-darwin"
           ;;
        *)
           echo "$TRIPLET"
    esac    
}

check_general_prerequisites() {
    check_tools

    MIR_JSON_INSTALL_DIR="${MIR_JSON_INSTALL_DIR:-${HOME}/.mir-json-up}"
    MIR_JSON_VERSION="${MIR_JSON_VERSION:-master}"
    MIR_JSON_RUST_TOOLCHAIN="${MIR_JSON_RUST_TOOLCHAIN:-$(get_toolchain_from_version ${MIR_JSON_VERSION})}"
    TARGET_TRIPLET="${TARGET_TRIPLET:-$(target_triplet_from_cc)}"
}

check_all_prerequisites() {
    check_general_prerequisites

    check_rust_toolchain

    require_rust_component rust-src
    require_rust_component rustc-dev
}

build_env() {
    cat <<EOF >> "${MIR_JSON_INSTALL_DIR}/env"
#!/bin/sh
case ":\${PATH}:" in
   *:"${MIR_JSON_INSTALL_DIR}/default/bin":*)
       ;;
   *)
       export PATH="${MIR_JSON_INSTALL_DIR}/default/bin:$PATH"
esac
export CRUX_RUST_LIBRARY_PATH="${MIR_JSON_INSTALL_DIR}/default/rlibs"
EOF
}

display_help() {
    echo "Usage: mir-json-up [--install-dir DIR] [--mir-json-version GIT-REF]"
    echo "         [--mir-json-rust-toolchain RUST-TOOLCHAIN] [--target-triplet TRIPLET] command"
    echo "Options:"
    echo "   --install-dir        Directory holding the 'mir-json-up' installation"
    echo "                            (default \$HOME/.mir-json-up)"
    echo "   --mir-json-version   Git reference for the version of 'mir-json' to use/install"
    echo "                            (default 'master')"
    echo "   --mir-json-rust-toolchain     Rust toolchain to use (default 'nightly-2025-09-14')"
    echo "   --target-triplet     Target triplet to use (default is the output of cc -dumpmachine)"
    echo "Commands:"
    echo "  mir-json-up check     Check if all requirements are in place for building 'mir-json'"
    echo "  mir-json-up help      Display this help"
    echo "  mir-json-up init      Install 'mir-json-up'"
    echo "  mir-json-up install   Download and build a specific version of 'mir-json' for a specific target"
    echo "  mir-json-up list      List all version/target 'mir-json' combinations installed"
    echo "  mir-json-up remove    Remove the given 'mir-json' version/target combination"
    echo "  mir-json-up run       Run a command within the active 'mir-json' version/target combination"
    echo "  mir-json-up set       Set the active 'mir-json' version/target combination"
}

SCRIPT_FILE=$(realpath "$0")

while (( "$#" )); do
    case "$1" in
        "--install-dir")
            MIR_JSON_INSTALL_DIR="$2"
            shift 2
            ;;
        "--mir-json-version")
            MIR_JSON_VERSION="$2"
            shift 2
            ;;
        "--mir-json-rust-toolchain")
            MIR_JSON_RUST_TOOLCHAIN="$2"
            shift 2
            ;;
        "--target-triplet")
            TARGET_TRIPLET="$2"
            shift 2
            ;;
        check|init|install|list|remove|run|set)
            COMMAND="$1"
            shift 1
            if [[ "$1" == "--" ]]; then
                shift 1
            fi
            break
            ;;
        help)
            display_help
            exit 0
            ;;
        *)
            echo "Invalid command: $1"
            exit 1
            ;;
    esac
done

COMMAND="${COMMAND:-help}"

case "$COMMAND" in
    check)
        check_all_prerequisites
        echo "All prerequisites in place"
        echo "  Rust toolchain: $MIR_JSON_RUST_TOOLCHAIN"
        echo "  Installing into: $MIR_JSON_INSTALL_DIR"
        echo "  Target: $TARGET_TRIPLET"
        ;;
    init)
        check_all_prerequisites
        create_installation_dir
        build_env        
        echo "Successfully initialized mir-json-up"
	    echo "To configure a shell, run or insert the following into your initialization script:"
        echo "  . ${MIR_JSON_INSTALL_DIR}/env"
        ;;
    install)
        check_all_prerequisites
        if [[ ! -d "${MIR_JSON_INSTALL_DIR}" ]]; then
            echo "${MIR_JSON_INSTALL_DIR} does not exist"
            exit 1
        fi
        get_mir_json_src
        build_mir_json
        ;;
    list)
        check_general_prerequisites
        if [[ ! -e "${MIR_JSON_INSTALL_DIR}" ]]; then
            echo "${MIR_JSON_INSTALL_DIR} does not exist"
            exit 1
        fi
        cd "${MIR_JSON_INSTALL_DIR}/toolchains"
        find */*/* -maxdepth 0 -type d
        ;;
    remove)
        check_general_prerequisites
        if [[ ! -e "${MIR_JSON_INSTALL_DIR}" ]]; then
            echo "${MIR_JSON_INSTALL_DIR} does not exist"
            exit 1
        fi
        local TOOLCHAIN_DIR="$(get_toolchain_dir)"
        rm -rf "${TOOLCHAIN_DIR}"
        ;;
    run)
        check_all_prerequisites
        if [[ ! -e "${MIR_JSON_INSTALL_DIR}/env" ]]; then
            echo "Cannot run before building: ${MIR_JSON_INSTALL_DIR}/env does not exist"
            exit 1
        fi
        . "${MIR_JSON_INSTALL_DIR}/env"
        $@
        ;;
    set)
        check_general_prerequisites
        create_default_symlinks "$(get_toolchain_dir)"
        ;;
    help)
        display_help
        exit 1
        ;;
    *)
        echo "Invalid command: ${COMMAND}"
        exit 1
        ;;
esac